---
version: "2.1"
services:
  app:
    build: .
    restart: always
    ports:
      - 8000:8000
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    user: root
    environment:
      - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=admin
    networks:
      - vpn
  mongodb:
    image: mongo:6.0.5
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    env_file:
      - .env
    ports:
      - 27017:27017
    networks:
      - vpn
networks:
  vpn:
    driver: bridge
